app:
  name: kakaopay-pretest-2
  description: Kakaopay Pretest 2 Server

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  jpa:
    database: h2